// <auto-generated />
using FakeBackend.Server.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FakeBackend.Server.Migrations
{
    [DbContext(typeof(FakeDBContext))]
    [Migration("20241023122113_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("FakeBackend.Server.Models.DTask", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("tag")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("id");

                    b.ToTable("DTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
